from PIL import Image

def make_pdf():
	background = Image.open(r'background_image.png')
	top_from = Image.open(r'efro_text.png')
	top_eto = Image.open(r'emto_text.png')
	top_message = Image.open(r'msg_text.png')
	top_subj = Image.open(r'subj_text.png')
	top_date = Image.open(r'date_text.png')

	back_rgb = background.convert('RGB')

	## Making copies so that original PNG is not altered
	# Background Layer
	lay01_bot = back_rgb.copy()
	# Input PNGS to paste 
	lay02_eto = top_eto.copy()
	lay03_efr = top_from.copy()
	lay04_sub = top_subj.copy()
	lay05_msg = top_message.copy()
	# Date is autogenerated
	lay06_dat = top_date.copy()

	#Paste All Inputs onto Bottom Layer
	lay01_bot.paste(lay02_eto,(230,220))
	lay01_bot.paste(lay03_efr,(230, 500))
	lay01_bot.paste(lay04_sub,(230,780))
	lay01_bot.paste(lay05_msg,(230,1070))
	#Paste Date
	lay01_bot.paste(lay06_dat,(1745,230))


	#Save as PDF, specifying resolution to keep dimensions
	lay01_bot.save(r'newpdf.pdf', resolution = 300.0)
